import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import styles from '../styles/Home.module.css'
import styles1 from '../styles/Home1.module.css'
import styles2 from '../styles/Home2.module.css'
import Link from  'next/link'
export default function Home() {
  console.log(styles)
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script> </Script> */}
      {/* <Script> alert("Hello")</Script> */}
      <nav className={styles.mainnav}>
        <ul>
        {/* <Link href='/home'> <a><li>Home</li></a></Link>   */}

        <li> <Link href="/home"><a>Home</a></Link></li>
        <li> <Link href="/about"><a>About</a></Link></li>
        <li> <Link href="/blog"><a>Blog</a></Link></li>
        <li> <Link href="/contact"><a>Contact</a></Link></li>
        
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Hunting Coder</a>
        </h1>

        <p className={styles.description}>
          A blog for hunting Coders by a hunting Coder
        </p>
        <div className={`${styles1.con}${styles2.con}`} >

        <h2>Popular Blogs</h2>
        <h3>How to learn Javascripts in 2022?</h3>
        <p>JavaScripts is a language for design  logic for web.</p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
