import Head from 'next/head'

import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      



        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Hunting Coder</a>
        </h1>
        <Image className={styles.img} src="/image.jpeg"
          alt="Picture of the author"
          width={150}
          height={150} />
        <p className={styles.description}>
          A blog for hunting Coders by a hunting Coder Lorem,
        </p>
        {/* <div className={`${styles1.con}${styles2.con}`} > */}
        <div>

          <h2 className={styles.h2}>Latest Blogs</h2>
          <div>
            <h3 className={styles.h3} >How to learn Javascripts in 2022?</h3>
            <p className={styles.p}>JavaScripts is a language for design  logic for web Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam odit nisi neque maiores
              dolor!.</p>
            <button className={styles.btn}>Read more</button>
          </div>
          <div>
            <h3 className={styles.h3} >How to learn Javascripts in 2022?</h3>
            <p className={styles.p}>JavaScripts is a language for design  logic for web
              dolor!.</p>
            <button className={styles.btn}>Read more</button>
          </div>
          <div>
            <h3 className={styles.h3} >How to learn Javascripts in 2022?</h3>
            <p className={styles.p}>JavaScripts is a language for design  logic for web
              dolor!.</p>
            <button className={styles.btn}>Read more</button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        Kishore Kumar
      </footer>
    </div>
  )
}
