import Head from 'next/head'

// import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  console.log(styles)
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Hunting Coder</a>
        </h1>

        <p className={styles.description}>
          A blog for hunting Coders by a hunting Coder
        </p>
        {/* <div className={`${styles1.con}${styles2.con}`} > */}
        <div>

        <h2 className='test'>Popular Blogs</h2>
        <h3>How to learn Javascripts in 2022?</h3>
        <p>JavaScripts is a language for design  logic for web.</p>
        </div>
      </main>

      <footer className={styles.footer}>
      Kishore Kumar
      </footer>
    </div>
  )
}
